linters-settings:

  gocritic:
    disabled-checks:
      - ifElseChain

linters:
  enable:
    - gosec
    - gofmt
    - gocritic
    - prealloc
    - misspell
    - nilerr
    - nilnil
  disable:
    - ineffassign

run:
  skip-files:
    - _gen.go
    - .generated.go

