FROM golang:1.21-alpine AS build
WORKDIR /go/src/go_my_pet_mac/go_my_pet

RUN apk add --no-cache make build-base git
COPY . .

FROM alpine:3 AS runtime
WORKDIR /app



COPY --from=build go/src/go_my_pet_mac/go_my_pet/bin/usr_mac usr
RUN chmod -v +x usr

ENTRYPOINT ["./usr"]